version: "3.9"

networks:
  yingxue_network:

volumes:
  data:
  redisdata:

services:
  nacos:
    image: nacos/nacos-server:2.0.2
    container_name: nacos
    ports:
      - "8848:8848"
    environment:
      - "JVM_XMS=265m"
      - "JVM_XMX=265m"
      - "MODE=standalone"
    networks:
      - yingxue_network

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    networks:
      - yingxue_network
    volumes:
      - data:/var/lib/mysql
      - ./yingxue.sql:/docker-entrypoint-initdb.d/yingxue.sql
    environment:
      - "MYSQL_ROOT_PASSWORD=17851182"
      - "MYSQL_DATABASE=yingxue"

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass 17851182
    ports:
      - "6379:6379"
    networks:
      - yingxue_network
    volumes:
      - redisdata:/data


  admins:
    build:
      context: ./images/admin
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - redis
      - nacos

  category:
    build:
      context: ./images/category
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - redis
      - nacos

  gateway:
    build:
      context: ./images/gateway
      dockerfile: Dockerfile
    ports:
      - "8899:8899"
    depends_on:
      - mysql
      - redis
      - nacos

  users:
    build:
      context: ./images/users
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - mysql
      - redis
      - nacos

  videos:
    build:
      context: ./images/videos
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - mysql
      - redis
      - nacos

#  nginx:
#    image: nginx:1.21.1
#    ports:
#      - "80:80"
#   最后的ro是readonly只读
#    volumes:
#      - ./admin-dist:/usr/share/nginx/html:ro
