#设置端口号
server:
  port: 8083
spring:
  application:
    name: API-USERS
  cloud:
    nacos:
      discovery:
        server-addr: 101.200.190.58:8848                  #配置nacos地址
        namespace: e95c430e-a3e1-4f10-babe-e59d16aafbec   #命名空间

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.200.190.58:3306/yingxue?characterEncoding=utf-8&useSSL=false&serverTimeZone=Asia/Shanghai
    username: root
    password: 17851182

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.azure.entity

logging:
  level:
    root: info
    com.azure.mapper: debug